POST https://shortener-radenrishwan.vercel.app/api/url
Content-Type: application/json

{
  "destination": "www.google.com",
  "alias": "hello"
}

###

GET http://localhost:3000/api/url?alias=welp

###
POST https://shortener-radenrishwan.vercel.app/api/url
Content-Type: application/json

{
  "destination": "www.google.com",
  "alias": "hello"
}

###